//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string MovieCategory { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
